### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by YikJiang-bs** [yutianqaq/x2Ldr#2]
报错SIGSEGV: illegal storage access. (Attempt to read from nil?)是为啥呢

**Comment by yutianqaq** [comment]
和 user.dat 放在一起

**Comment by YikJiang-bs** [comment]
为啥我没看到user.data
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yutianqaq/x2Ldr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月26日(星期二) 下午3:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yutianqaq/x2Ldr] 报错 (Issue #2)





 
和 user.dat 放在一起

**Comment by yutianqaq** [comment]
代码里写着呢，你可以将 xor 脚本加密后的文件名改为 user.dat

**Comment by YikJiang-bs** [comment]
好的好的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yutianqaq/x2Ldr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月26日(星期二) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yutianqaq/x2Ldr] 报错 (Issue #2)





 
代码里写着呢，你可以将 xor 脚本加密后的文件名改为 user.dat
