### ISSUE TITLE
编译后运行没反应，是不是没改对？

### ISSUE THREAD

**Issue by Kar1chan** [yutianqaq/x2Ldr#3]
将加密后的文件名作为参数传递给 nim 文件中的 fopen 参数

	//修改这里
	char key[] = "key";

	//修改这里
	fp = fopen("user.dat", "rb");

这里我用py加密bin之后新生成的文件名改成了user.dat，然后你说的
	//修改这里
	char key[] = "key";

这里是需要修改什么？谢谢

**Comment by Kar1chan** [comment]
运行的问题解决了，有个问题是不能单独把生成的exe拿出来用吗？我移到别的文件夹内运行就报错，必须在这个项目的文件夹内？

**Comment by yutianqaq** [comment]
需要和user.dat 放一起，user.dat 名字可以自定义
