### ISSUE TITLE
ille storage access attempt to read from nil?

### ISSUE THREAD

**Issue by pluto-chou** [yutianqaq/x2Ldr#5]
![U O9AO }0%PY08XAI%~92S](https://github.com/yutianqaq/x2Ldr/assets/128489672/83e213f0-e6f2-4ea4-a07a-6d99ca78e177)
佬，这个问题怎么解决

**Comment by yutianqaq** [comment]
和user.dat 放一起

**Comment by pluto-chou** [comment]
![1](https://github.com/yutianqaq/x2Ldr/assets/128489672/bfd1bf54-bf54-400c-9a8e-4ff68cdd8896)
![2](https://github.com/yutianqaq/x2Ldr/assets/128489672/5be3d076-6e49-4fb1-b659-18cc5a77d0de)
![3](https://github.com/yutianqaq/x2Ldr/assets/128489672/d7a516c9-d33b-4108-a351-e398759a88b9)
佬，将被xor的的文件改为user.dat之后，不能成功跳出计算器出来，就转一下圈圈如何就没了

**Comment by yutianqaq** [comment]
你最后一个图是 x2LdrPlus.nim的对吧，这个可以单独运行。
应该是你的编译命令错了 nim c xxxx ./x2LdrPlus.nim

**Comment by pluto-chou** [comment]
感谢大佬，大佬牛逼啊！大佬我爱你
